[pytest]
testpaths = Tests
python_files = test_*.py
python_functions = test_*

markers =
    ui: Selenium UI tests
    unit: Unit tests
    integration: Integration tests
    smoke: Smoke tests
    critical: Critical path tests